"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Flow__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var Flow__factory_js_1 = require("./Flow__factory.js");
Object.defineProperty(exports, "Flow__factory", { enumerable: true, get: function () { return Flow__factory_js_1.Flow__factory; } });
//# sourceMappingURL=index.js.map