"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FixedPriceFlow__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var FixedPriceFlow__factory_js_1 = require("./FixedPriceFlow__factory.js");
Object.defineProperty(exports, "FixedPriceFlow__factory", { enumerable: true, get: function () { return FixedPriceFlow__factory_js_1.FixedPriceFlow__factory; } });
//# sourceMappingURL=index.js.map