"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.FixedPrice__factory = void 0;
/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
var FixedPrice__factory_js_1 = require("./FixedPrice__factory.js");
Object.defineProperty(exports, "FixedPrice__factory", { enumerable: true, get: function () { return FixedPrice__factory_js_1.FixedPrice__factory; } });
//# sourceMappingURL=index.js.map